// Code generated by MockGen. DO NOT EDIT.
// Source: lock.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	go_redislock "github.com/jefferyjob/go-redislock"
)

// MockRedisInter is a mock of RedisInter interface.
type MockRedisInter struct {
	ctrl     *gomock.Controller
	recorder *MockRedisInterMockRecorder
}

// MockRedisInterMockRecorder is the mock recorder for MockRedisInter.
type MockRedisInterMockRecorder struct {
	mock *MockRedisInter
}

// NewMockRedisInter creates a new mock instance.
func NewMockRedisInter(ctrl *gomock.Controller) *MockRedisInter {
	mock := &MockRedisInter{ctrl: ctrl}
	mock.recorder = &MockRedisInterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisInter) EXPECT() *MockRedisInterMockRecorder {
	return m.recorder
}

// Eval mocks base method.
func (m *MockRedisInter) Eval(ctx context.Context, script string, keys []string, args ...interface{}) go_redislock.RedisCmd {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, script, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Eval", varargs...)
	ret0, _ := ret[0].(go_redislock.RedisCmd)
	return ret0
}

// Eval indicates an expected call of Eval.
func (mr *MockRedisInterMockRecorder) Eval(ctx, script, keys interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, script, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eval", reflect.TypeOf((*MockRedisInter)(nil).Eval), varargs...)
}

// MockRedisCmd is a mock of RedisCmd interface.
type MockRedisCmd struct {
	ctrl     *gomock.Controller
	recorder *MockRedisCmdMockRecorder
}

// MockRedisCmdMockRecorder is the mock recorder for MockRedisCmd.
type MockRedisCmdMockRecorder struct {
	mock *MockRedisCmd
}

// NewMockRedisCmd creates a new mock instance.
func NewMockRedisCmd(ctrl *gomock.Controller) *MockRedisCmd {
	mock := &MockRedisCmd{ctrl: ctrl}
	mock.recorder = &MockRedisCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisCmd) EXPECT() *MockRedisCmdMockRecorder {
	return m.recorder
}

// Int64 mocks base method.
func (m *MockRedisCmd) Int64() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int64")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Int64 indicates an expected call of Int64.
func (mr *MockRedisCmdMockRecorder) Int64() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int64", reflect.TypeOf((*MockRedisCmd)(nil).Int64))
}

// Result mocks base method.
func (m *MockRedisCmd) Result() (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Result")
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Result indicates an expected call of Result.
func (mr *MockRedisCmdMockRecorder) Result() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Result", reflect.TypeOf((*MockRedisCmd)(nil).Result))
}

// MockRedisLockInter is a mock of RedisLockInter interface.
type MockRedisLockInter struct {
	ctrl     *gomock.Controller
	recorder *MockRedisLockInterMockRecorder
}

// MockRedisLockInterMockRecorder is the mock recorder for MockRedisLockInter.
type MockRedisLockInterMockRecorder struct {
	mock *MockRedisLockInter
}

// NewMockRedisLockInter creates a new mock instance.
func NewMockRedisLockInter(ctrl *gomock.Controller) *MockRedisLockInter {
	mock := &MockRedisLockInter{ctrl: ctrl}
	mock.recorder = &MockRedisLockInterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisLockInter) EXPECT() *MockRedisLockInterMockRecorder {
	return m.recorder
}

// FairLock mocks base method.
func (m *MockRedisLockInter) FairLock(ctx context.Context, requestId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FairLock", ctx, requestId)
	ret0, _ := ret[0].(error)
	return ret0
}

// FairLock indicates an expected call of FairLock.
func (mr *MockRedisLockInterMockRecorder) FairLock(ctx, requestId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FairLock", reflect.TypeOf((*MockRedisLockInter)(nil).FairLock), ctx, requestId)
}

// FairRenew mocks base method.
func (m *MockRedisLockInter) FairRenew(ctx context.Context, requestId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FairRenew", ctx, requestId)
	ret0, _ := ret[0].(error)
	return ret0
}

// FairRenew indicates an expected call of FairRenew.
func (mr *MockRedisLockInterMockRecorder) FairRenew(ctx, requestId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FairRenew", reflect.TypeOf((*MockRedisLockInter)(nil).FairRenew), ctx, requestId)
}

// FairUnLock mocks base method.
func (m *MockRedisLockInter) FairUnLock(ctx context.Context, requestId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FairUnLock", ctx, requestId)
	ret0, _ := ret[0].(error)
	return ret0
}

// FairUnLock indicates an expected call of FairUnLock.
func (mr *MockRedisLockInterMockRecorder) FairUnLock(ctx, requestId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FairUnLock", reflect.TypeOf((*MockRedisLockInter)(nil).FairUnLock), ctx, requestId)
}

// Lock mocks base method.
func (m *MockRedisLockInter) Lock(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockRedisLockInterMockRecorder) Lock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockRedisLockInter)(nil).Lock), ctx)
}

// Renew mocks base method.
func (m *MockRedisLockInter) Renew(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockRedisLockInterMockRecorder) Renew(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockRedisLockInter)(nil).Renew), ctx)
}

// SpinFairLock mocks base method.
func (m *MockRedisLockInter) SpinFairLock(ctx context.Context, requestId string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpinFairLock", ctx, requestId, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpinFairLock indicates an expected call of SpinFairLock.
func (mr *MockRedisLockInterMockRecorder) SpinFairLock(ctx, requestId, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpinFairLock", reflect.TypeOf((*MockRedisLockInter)(nil).SpinFairLock), ctx, requestId, timeout)
}

// SpinLock mocks base method.
func (m *MockRedisLockInter) SpinLock(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpinLock", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpinLock indicates an expected call of SpinLock.
func (mr *MockRedisLockInterMockRecorder) SpinLock(ctx, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpinLock", reflect.TypeOf((*MockRedisLockInter)(nil).SpinLock), ctx, timeout)
}

// UnLock mocks base method.
func (m *MockRedisLockInter) UnLock(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnLock", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnLock indicates an expected call of UnLock.
func (mr *MockRedisLockInterMockRecorder) UnLock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnLock", reflect.TypeOf((*MockRedisLockInter)(nil).UnLock), ctx)
}
